# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('done', 'done')], default='scheduler', max_length=10),
        ),
    ]
