# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20160831_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keywords',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('done', 'done')], default='scheduled', max_length=10),
        ),
    ]
