# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20160831_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='google_status',
        ),
        migrations.AddField(
            model_name='task',
            name='instagram_status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('done', 'done')], default='scheduled', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='yandex_status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('done', 'done')], default='scheduled', max_length=10),
        ),
    ]
